"""Management Core package for UDS3 administrative services."""

from .lifecycle import (
    LifecycleConfigurationError,
    LifecycleManager,
    LifecycleRecord,
    LifecycleStateDefinition,
    LifecycleTransition,
    LifecycleTransitionError,
)
from .policy import (
    PolicyCheckResult,
    PolicyContext,
    PolicyDecision,
    PolicyEngine,
    PolicyEvaluationResult,
    PolicyRule,
    PolicySeverity,
    PolicyViolation,
)
from .registry import (
    RegistryEntry,
    RegistryHistoryRecord,
    RegistryReference,
    RegistryService,
)
from .management_core import (
    ManagementCore,
    ManagementCoreConfig,
)
from .vector_management import (
    VectorManagementService,
    VectorManagementConfig,
    VectorCollectionDefinition,
    VectorChunkPayload,
    VectorIngestResult,
    VectorManagementError,
)
from .graph_management import (
    GraphManagementService,
    GraphManagementConfig,
    GraphNodeTypeDefinition,
    GraphRelationshipDefinition,
    GraphNodePayload,
    GraphRelationshipPayload,
    GraphMutationResult,
    StoredGraphNode,
    StoredGraphRelationship,
    GraphManagementError,
)
from .relational_management import (
    RelationalManagementService,
    RelationalManagementConfig,
    RelationalTableDefinition,
    RelationalRecordPayload,
    RelationalMutationResult,
    StoredRelationalRecord,
    RelationalManagementError,
)
from .filesystem_management import (
    FileSystemManagementService,
    FileSystemManagementConfig,
    FileAssetPayload,
    FileDerivativePayload,
    StoredFileAsset,
    StoredFileDerivative,
    FileAssetIngestResult,
    FileDerivativeIngestResult,
    FileSystemManagementError,
)

__all__ = [
    "LifecycleConfigurationError",
    "LifecycleManager",
    "LifecycleRecord",
    "LifecycleStateDefinition",
    "LifecycleTransition",
    "LifecycleTransitionError",
    "PolicyCheckResult",
    "PolicyContext",
    "PolicyDecision",
    "PolicyEngine",
    "PolicyEvaluationResult",
    "PolicyRule",
    "PolicySeverity",
    "PolicyViolation",
    "RegistryEntry",
    "RegistryHistoryRecord",
    "RegistryReference",
    "RegistryService",
    "ManagementCore",
    "ManagementCoreConfig",
    "VectorManagementService",
    "VectorManagementConfig",
    "VectorCollectionDefinition",
    "VectorChunkPayload",
    "VectorIngestResult",
    "VectorManagementError",
    "GraphManagementService",
    "GraphManagementConfig",
    "GraphNodeTypeDefinition",
    "GraphRelationshipDefinition",
    "GraphNodePayload",
    "GraphRelationshipPayload",
    "GraphMutationResult",
    "StoredGraphNode",
    "StoredGraphRelationship",
    "GraphManagementError",
    "RelationalManagementService",
    "RelationalManagementConfig",
    "RelationalTableDefinition",
    "RelationalRecordPayload",
    "RelationalMutationResult",
    "StoredRelationalRecord",
    "RelationalManagementError",
    "FileSystemManagementService",
    "FileSystemManagementConfig",
    "FileAssetPayload",
    "FileDerivativePayload",
    "StoredFileAsset",
    "StoredFileDerivative",
    "FileAssetIngestResult",
    "FileDerivativeIngestResult",
    "FileSystemManagementError",
]
