#!/usr/bin/env python3
"""
Generate Covina Wiki content by aggregating Markdown docs from Covina/docs into Covina/wiki.

Differences vs root script version:
- Scoped ONLY to Covina/docs
- Writes output to Covina/wiki (sibling inside Covina project)
- Root auto-detection keeps Windows local path support
"""
from __future__ import annotations
import os
import shutil
from pathlib import Path
from datetime import datetime, UTC


def detect_covina_root() -> Path:
    """Detect Covina project root across local (Windows) and CI environments.

    Priority:
    1) COVINA_ROOT env var
    2) <repo>/Covina (monorepo layout)
    3) C:/VCC/Covina (local Windows default)
    4) current working directory if named 'Covina'
    5) fallback: <repo>/Covina (even if missing)
    """
    env = os.environ.get("COVINA_ROOT")
    if env:
        p = Path(env)
        if p.exists():
            return p
    repo_root = Path(__file__).resolve().parents[2]  # tools/ inside Covina/ inside repo
    candidate = repo_root / "Covina"
    if candidate.exists():
        return candidate
    win_default = Path(r"C:/VCC/Covina")
    if win_default.exists():
        return win_default
    cwd = Path.cwd()
    if cwd.name.lower() == "covina":
        return cwd
    return candidate


ROOT = detect_covina_root()
WIKI_DIR = ROOT / "wiki"
SOURCES = [
    (ROOT / "docs", "Covina"),
]
ASSET_EXT = {".png", ".jpg", ".jpeg", ".gif", ".svg", ".bmp", ".webp"}
MD_EXT = {".md", ".markdown"}


def safe_relpath(path: Path, start: Path) -> Path:
    try:
        return path.relative_to(start)
    except Exception:
        return Path(path.name)


def clean_output(dir_path: Path) -> None:
    if dir_path.exists():
        protected = {".git", ".gitkeep", ".gitignore", ".gitattributes"}
        for child in dir_path.iterdir():
            if child.name in protected:
                continue
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()
    else:
        dir_path.mkdir(parents=True, exist_ok=True)


def copy_tree(src: Path, dst_root: Path, namespace: str) -> int:
    if not src.exists():
        return 0
    dst_base = dst_root / namespace
    count = 0
    for path in src.rglob("*"):
        if not path.is_file():
            continue
        ext = path.suffix.lower()
        if ext not in MD_EXT and ext not in ASSET_EXT:
            continue
        rel = safe_relpath(path, src)
        out_path = dst_base / rel
        out_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, out_path)
        if ext in MD_EXT:
            count += 1
    return count


def build_home(md_counts: dict[str, int]) -> None:
    ts = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Covina Project Wiki",
        "",
        f"Generated on {ts}",
        "",
        "[Hinweis: Nicht manuell bearbeiten – siehe README_GENERATION.md](README_GENERATION.md)",
        "",
        "## Sections",
    ]
    if md_counts.get("Covina", 0) > 0:
        landing = None
        candidate = WIKI_DIR / "Covina" / "INDEX.md"
        if candidate.exists():
            landing = "Covina/INDEX.md"
        else:
            rd = WIKI_DIR / "Covina" / "README.md"
            if rd.exists():
                landing = "Covina/README.md"
            else:
                for p in (WIKI_DIR / "Covina").rglob("*.md"):
                    landing = "Covina/" + str(p.relative_to(WIKI_DIR / "Covina")).replace("\\", "/")
                    break
        if landing:
            lines.append(f"- [Covina]({landing}) ({md_counts['Covina']} docs)")
        else:
            lines.append(f"- Covina ({md_counts['Covina']} docs)")
    (WIKI_DIR / "Home.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_generation_readme() -> None:
    text = (
        "# Covina Wiki (Generated)\n\n"
        "Do not edit files in this folder manually.\n\n"
        "This directory is generated by `Covina/tools/generate_wiki.py` from the contents of `Covina/docs`.\n\n"
        "- Source: Covina/docs\n"
        "- Output: Covina/wiki\n"
        "- Workflow: .github/workflows/wiki.yml commits updates with [skip ci]\n\n"
    "To regenerate locally, run:\n\n"
    "```powershell\n"
    "powershell -NoLogo -NoProfile -ExecutionPolicy Bypass -File Covina/scripts/build_wiki.ps1\n"
    "```\n"
    )
    (WIKI_DIR / "README_GENERATION.md").write_text(text, encoding="utf-8")


def write_generation_readme_fixed() -> None:
    ts = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    content = f"""# Covina Wiki (Generated)

Nicht manuell bearbeiten – dieser Ordner wird automatisch erzeugt und beim nächsten Build überschrieben.

Quellen:
- Covina/docs/**

Build:
- GitHub Actions: .github/workflows/wiki.yml (Job: Build and Commit Covina Wiki)
- Lokal: Covina/scripts/build_wiki.ps1

Generator:
- Covina/tools/generate_wiki.py

Stand: {ts}

```powershell
# Lokal generieren
powershell -NoLogo -NoProfile -ExecutionPolicy Bypass -File Covina/scripts/build_wiki.ps1
```
"""
    (WIKI_DIR / "README_GENERATION.md").write_text(content, encoding="utf-8")


def main() -> int:
    print(f"Generating Covina wiki into: {WIKI_DIR}")
    clean_output(WIKI_DIR)
    md_counts: dict[str, int] = {}
    for src, ns in SOURCES:
        cnt = copy_tree(src, WIKI_DIR, ns)
        md_counts[ns] = cnt
        print(f" - {ns}: {cnt} markdown files")
    build_home(md_counts)
    write_generation_readme_fixed()
    (WIKI_DIR / ".gitkeep").touch(exist_ok=True)
    print("Wiki generation complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
